---
- name: Creation of new user
  hosts: all
  vars_files:
    - password.yml
  tasks:
    - name: Creating user
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ '{{password}}' | password_hash('sha512') }}"
        comment: "LILY"
        shell: /bin/sh
        createhome: true
        home: /home/lily
