---
- name: Creation of new user
  hosts: localhost
  vars_files:
    - password.yml
  tasks:
    - name: Creating user
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password }}"
        comment: "Main user"
        shell: /bin/bash
        createhome: true
        home: /home/chutki
