---
- name: Creation of new user
  hosts: all
  vars_files:
    - password.yml
  tasks:
    - name: Creating user
      ansible.builtin.user:
        name: manasa
        password: 1234
        comment: "Main user"
        shell: /bin/bash
        createhome: true
        home: /home/manasa
